### PR TITLE
updated C header generation for fixed_point

### LINKED ISSUE #51: write_C_header does not export fixed point numbers
https://github.com/hammal/cbadc/blob/a700a9c2b55b8f4ae9a75dfaa2b4f3fa7ff12da3/src/cbadc/digital_estimator.py#L1773

function exports floating point numbers even if estimator is set to fixed point

### PR DESCRIPTION
**Pull request by hammal**
Closes #51

<a href="https://gitpod.io/#https://github.com/hammal/cbadc/pull/59"></a>

### CODE REVIEW

**Review by kasettli — COMMENTED** [review]
I see an empty file: tests/unittest/test_utilities/__init__.py
@hammal you would know, wether this is supposed to be.

**Review by kasettli — APPROVED** [review]
The other two files look ok to me.

**Comment by hammal** [comment]
> I see an empty file: tests/unittest/test_utilities/**init**.py
> @hammal you would know, wether this is supposed to be.

Yeah @kasettli  that should be harmless (and pointless)

**Comment by hammal** [comment]
> The other two files look ok to me.

Thanks!

**Comment by hammal** [comment]
I'll merge if tests pass...

**Pull request merged**
